### ISSUE TITLE
Remover troca de cores

### ISSUE THREAD

**Issue by onhernandes** [felipealencar/antifascismo#1]
Oi!

Acho a ideia ótima e muito boa, facilita a representação do movimento antifascista para qualquer categoria. Porém, as cores vermelho e preto possuem significado histórico pro movimento, não deveriam ser removidos, até porque isso acaba criando divergências no movimento, essas que podem ser até controversas ao movimento em si. Um exemplo é a possibilidade de criar uma bandeira "integralistas antifascistas" (https://pt.wikipedia.org/wiki/A%C3%A7%C3%A3o_Integralista_Brasileira#S%C3%ADmbolos,_vestimentas,_rituais_e_iconografia)

Dito isso, sugiro remover o color-picker, mantendo as cores vermelho e preto, que foram historicamente usadas, não podemos apagar esse símbolo agora, onde mais precisamos de união.

Vale lembrar que a bandeira hoje é uma evolução/ramificação do movimento, mas as cores permanecem originais: https://pt.wikipedia.org/wiki/C%C3%ADrculo_Antifascista

**Comment by andrefelizardo** [comment]
Caramba, vim aqui escrever a mesma coisa que o @onhernandes escreveu. Sua ideia foi ótima, mas rola esse lance das cores!

Abraços

**Comment by icaro56** [comment]
https://github.com/icaro56/antifascismo

Removi aqui. Mas o dono do repositório precisa aceitar o pull request

Da pra usar localmente se vc pegar o código no meu repositorio

**Comment by icaro56** [comment]
Versão online: https://icaro56.github.io/antifascismo/

Aqui. Enquanto o autor não atualiza o repositorio dele. Todos os créditos são dele.

**Comment by felipealencar** [comment]
Olá, sinto pela demora.
Acabei entrando hoje nessa discussão das cores da bandeira. Mas ainda não pesei os prós e contras e vou deixar isso aberto por enquanto. Entendo perfeitamente a lógica por trás de manter a cor original, mas, por outro lado, grupos e categorias se envolveram na mobilização da divulgação por verem bandeiras em cores que as representavam também (e.g., grupos feministas, ambientas).

Gostaria que essa discussão fosse mais além, se possível, pra que a gente possa encontrar um denominador comum aí e colaborar em outras ferramentas que sejam úteis nesse momento.
Obrigado pela participação no projeto! Foi algo bem rápido feito na madrugada, mas é bom ver vocês contribuindo.
[]'s

**Comment by dipnlik** [comment]
Esbarrei neste issue justamente tentando me informar sobre o significado das cores.

Acho importante manter o colorpicker mas eu incluiria um link, textinho, tooltip, enfim alguma coisa simplesinha, esclarecendo a importância de manter o vermelho para significar o antifascismo, e se tiver link pra referência externa colocaria também. Assim ajuda os desinformados e ainda permite que outros movimentos consigam seguir usando a ferramenta.

**Comment by onhernandes** [comment]
Então, a questão é que as cores fazem parte diretamente do movimento antifascista. Alterar isso cria uma ramificação desnecessária em cima disso. A bandeira LGBT+ por exemplo, tem suas cores e ninguém remove ou adiciona uma cor pra representar a classe operária, por exemplo, ou veganismo, etc. Fora que a mudança desenfreada das cores não só ignora e apaga o histórico de luta do movimento, como também pode levar à interpretações erradas, como foi o exemplo que deixei do movimento integralista brasileiro ao usar verde e preto, ou azul.

E também, tem outros pontos, como: o movimento antifascista por si só é anticapitalista. Não tem como se juntar à causa sem aceitar isso e lutar contra o capitalismo. Algumas definições resumem o vermelho ao socialismo e o preto ao comunismo.

A luta em si é representada pela bandeira e pelas cores, não podemos remover isso. Vejo que incluir outras categorias e movimentos na luta antifascista é uma coisa totalmente diferente de desrespeitar e ressignificar o movimento antifascista. 

Compreendo também que com o passar do tempo, símbolos e representações correm o risco de serem ressignificados, mas isso não deixa de ser arriscado

Sugiro remover o color-picker e deixar um explicativo e algumas referências sobre o porque manter as cores originais e porque não troca-las.
